# Generated by Django 5.1.6 on 2025-05-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_comment_options_comment_author_thread_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum/'),
        ),
    ]
