# Generated by Django 5.1.6 on 2025-05-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_profile_mobile_alter_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
