# Generated by Django 5.1.6 on 2025-03-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'verbose_name': 'product type', 'verbose_name_plural': 'product types'},
        ),
    ]
