# Generated by Django 5.1.6 on 2025-05-12 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_alter_producttype_options'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('S', 'On sale'), ('O', 'Out of stock')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'On cart'), ('P', 'To pay'), ('S', 'To ship'), ('R', 'To receive'), ('D', 'Delivered')], default='C', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='user_management.profile')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='merchstore.product')),
            ],
        ),
    ]
