# Generated by Django 5.1.6 on 2025-03-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_comment_commission_alter_comment_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='decription',
            new_name='description',
        ),
    ]
