<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-05-03 11:52
=======
# Generated by Django 5.1.6 on 2025-05-06 08:52
>>>>>>> b8035b81a6f271f70dcc5e25cc04eeec99748412

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_rename_decription_commission_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-created_on']},
        ),
    ]
