# Generated by Django 5.1.6 on 2025-05-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_alter_comment_options_alter_commission_options'),
        ('commissions', '0004_alter_comment_options_alter_commission_options_and_more'),
    ]

    operations = [
    ]
