# Generated by Django 5.1.6 on 2025-05-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_author_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='last_updated',
            new_name='updated_on',
        ),
    ]
