# Generated by Django 5.1.6 on 2025-05-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_last_updated_article_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(null=True, upload_to='blog/headers/'),
        ),
    ]
